//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConsoleLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Terasievert.AbonConsole.AntlrGenerated {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class ConsoleLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EXCLAIM=1, EQ=2, COMMA=3, SEMI=4, LPAREN=5, RPAREN=6, DOT=7, NEW=8, HELP=9, 
		TRUE=10, FALSE=11, NULL=12, PLUS=13, MINUS=14, MULT=15, DIV=16, DOLLAR=17, 
		INT=18, LONG=19, FLOAT=20, DOUBLE=21, ID=22, WS=23, STR=24, CHAR=25, ERROR=26;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"EXCLAIM", "EQ", "COMMA", "SEMI", "LPAREN", "RPAREN", "DOT", "NEW", "HELP", 
		"TRUE", "FALSE", "NULL", "PLUS", "MINUS", "MULT", "DIV", "DOLLAR", "DIGITS", 
		"INT", "LONG", "FLOAT", "DOUBLE", "ID", "WS", "STR", "CHAR", "ERROR"
	};


	public ConsoleLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ConsoleLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'!'", "'='", "','", "';'", "'('", "')'", "'.'", "'new'", "'help'", 
		"'true'", "'false'", "'null'", "'+'", "'-'", "'*'", "'/'", "'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EXCLAIM", "EQ", "COMMA", "SEMI", "LPAREN", "RPAREN", "DOT", "NEW", 
		"HELP", "TRUE", "FALSE", "NULL", "PLUS", "MINUS", "MULT", "DIV", "DOLLAR", 
		"INT", "LONG", "FLOAT", "DOUBLE", "ID", "WS", "STR", "CHAR", "ERROR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ConsoleLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ConsoleLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,26,173,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,1,0,1,0,1,1,1,1,
		1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,
		8,1,8,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,10,1,11,1,11,1,11,
		1,11,1,11,1,12,1,12,1,13,1,13,1,14,1,14,1,15,1,15,1,16,1,16,1,17,4,17,
		106,8,17,11,17,12,17,107,1,18,3,18,111,8,18,1,18,1,18,1,19,1,19,1,19,1,
		20,3,20,119,8,20,1,20,1,20,1,20,3,20,124,8,20,1,20,3,20,127,8,20,1,20,
		3,20,130,8,20,1,20,1,20,3,20,134,8,20,1,21,1,21,1,21,1,22,1,22,5,22,141,
		8,22,10,22,12,22,144,9,22,1,23,4,23,147,8,23,11,23,12,23,148,1,23,1,23,
		1,24,1,24,1,24,1,24,5,24,157,8,24,10,24,12,24,160,9,24,1,24,1,24,1,25,
		1,25,1,25,1,25,3,25,168,8,25,1,25,1,25,1,26,1,26,0,0,27,1,1,3,2,5,3,7,
		4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,31,16,33,
		17,35,0,37,18,39,19,41,20,43,21,45,22,47,23,49,24,51,25,53,26,1,0,10,1,
		0,48,57,2,0,76,76,108,108,2,0,68,68,100,100,3,0,65,90,95,95,97,122,4,0,
		48,57,65,90,95,95,97,122,3,0,9,10,12,13,32,32,2,0,34,34,92,92,4,0,34,34,
		65,90,92,92,97,122,2,0,39,39,92,92,4,0,39,39,65,90,92,92,97,122,183,0,
		1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,
		0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,
		1,0,0,0,0,25,1,0,0,0,0,27,1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,
		0,0,37,1,0,0,0,0,39,1,0,0,0,0,41,1,0,0,0,0,43,1,0,0,0,0,45,1,0,0,0,0,47,
		1,0,0,0,0,49,1,0,0,0,0,51,1,0,0,0,0,53,1,0,0,0,1,55,1,0,0,0,3,57,1,0,0,
		0,5,59,1,0,0,0,7,61,1,0,0,0,9,63,1,0,0,0,11,65,1,0,0,0,13,67,1,0,0,0,15,
		69,1,0,0,0,17,73,1,0,0,0,19,78,1,0,0,0,21,83,1,0,0,0,23,89,1,0,0,0,25,
		94,1,0,0,0,27,96,1,0,0,0,29,98,1,0,0,0,31,100,1,0,0,0,33,102,1,0,0,0,35,
		105,1,0,0,0,37,110,1,0,0,0,39,114,1,0,0,0,41,133,1,0,0,0,43,135,1,0,0,
		0,45,138,1,0,0,0,47,146,1,0,0,0,49,152,1,0,0,0,51,163,1,0,0,0,53,171,1,
		0,0,0,55,56,5,33,0,0,56,2,1,0,0,0,57,58,5,61,0,0,58,4,1,0,0,0,59,60,5,
		44,0,0,60,6,1,0,0,0,61,62,5,59,0,0,62,8,1,0,0,0,63,64,5,40,0,0,64,10,1,
		0,0,0,65,66,5,41,0,0,66,12,1,0,0,0,67,68,5,46,0,0,68,14,1,0,0,0,69,70,
		5,110,0,0,70,71,5,101,0,0,71,72,5,119,0,0,72,16,1,0,0,0,73,74,5,104,0,
		0,74,75,5,101,0,0,75,76,5,108,0,0,76,77,5,112,0,0,77,18,1,0,0,0,78,79,
		5,116,0,0,79,80,5,114,0,0,80,81,5,117,0,0,81,82,5,101,0,0,82,20,1,0,0,
		0,83,84,5,102,0,0,84,85,5,97,0,0,85,86,5,108,0,0,86,87,5,115,0,0,87,88,
		5,101,0,0,88,22,1,0,0,0,89,90,5,110,0,0,90,91,5,117,0,0,91,92,5,108,0,
		0,92,93,5,108,0,0,93,24,1,0,0,0,94,95,5,43,0,0,95,26,1,0,0,0,96,97,5,45,
		0,0,97,28,1,0,0,0,98,99,5,42,0,0,99,30,1,0,0,0,100,101,5,47,0,0,101,32,
		1,0,0,0,102,103,5,36,0,0,103,34,1,0,0,0,104,106,7,0,0,0,105,104,1,0,0,
		0,106,107,1,0,0,0,107,105,1,0,0,0,107,108,1,0,0,0,108,36,1,0,0,0,109,111,
		5,45,0,0,110,109,1,0,0,0,110,111,1,0,0,0,111,112,1,0,0,0,112,113,3,35,
		17,0,113,38,1,0,0,0,114,115,3,37,18,0,115,116,7,1,0,0,116,40,1,0,0,0,117,
		119,5,45,0,0,118,117,1,0,0,0,118,119,1,0,0,0,119,120,1,0,0,0,120,121,3,
		35,17,0,121,123,5,46,0,0,122,124,3,35,17,0,123,122,1,0,0,0,123,124,1,0,
		0,0,124,134,1,0,0,0,125,127,5,45,0,0,126,125,1,0,0,0,126,127,1,0,0,0,127,
		129,1,0,0,0,128,130,3,35,17,0,129,128,1,0,0,0,129,130,1,0,0,0,130,131,
		1,0,0,0,131,132,5,46,0,0,132,134,3,35,17,0,133,118,1,0,0,0,133,126,1,0,
		0,0,134,42,1,0,0,0,135,136,3,41,20,0,136,137,7,2,0,0,137,44,1,0,0,0,138,
		142,7,3,0,0,139,141,7,4,0,0,140,139,1,0,0,0,141,144,1,0,0,0,142,140,1,
		0,0,0,142,143,1,0,0,0,143,46,1,0,0,0,144,142,1,0,0,0,145,147,7,5,0,0,146,
		145,1,0,0,0,147,148,1,0,0,0,148,146,1,0,0,0,148,149,1,0,0,0,149,150,1,
		0,0,0,150,151,6,23,0,0,151,48,1,0,0,0,152,158,5,34,0,0,153,157,8,6,0,0,
		154,155,5,92,0,0,155,157,7,7,0,0,156,153,1,0,0,0,156,154,1,0,0,0,157,160,
		1,0,0,0,158,156,1,0,0,0,158,159,1,0,0,0,159,161,1,0,0,0,160,158,1,0,0,
		0,161,162,5,34,0,0,162,50,1,0,0,0,163,167,5,39,0,0,164,168,8,8,0,0,165,
		166,5,92,0,0,166,168,7,9,0,0,167,164,1,0,0,0,167,165,1,0,0,0,168,169,1,
		0,0,0,169,170,5,39,0,0,170,52,1,0,0,0,171,172,9,0,0,0,172,54,1,0,0,0,13,
		0,107,110,118,123,126,129,133,142,148,156,158,167,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Terasievert.AbonConsole.AntlrGenerated
