//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConsoleParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Terasievert.AbonConsole.AntlrGenerated {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class ConsoleParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EXCLAIM=1, EQ=2, COMMA=3, SEMI=4, LPAREN=5, RPAREN=6, DOT=7, NEW=8, HELP=9, 
		TRUE=10, FALSE=11, NULL=12, PLUS=13, MINUS=14, MULT=15, DIV=16, DOLLAR=17, 
		INT=18, LONG=19, FLOAT=20, DOUBLE=21, ID=22, WS=23, STR=24, CHAR=25, ERROR=26;
	public const int
		RULE_statement = 0, RULE_command = 1, RULE_expr = 2, RULE_argList = 3;
	public static readonly string[] ruleNames = {
		"statement", "command", "expr", "argList"
	};

	private static readonly string[] _LiteralNames = {
		null, "'!'", "'='", "','", "';'", "'('", "')'", "'.'", "'new'", "'help'", 
		"'true'", "'false'", "'null'", "'+'", "'-'", "'*'", "'/'", "'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EXCLAIM", "EQ", "COMMA", "SEMI", "LPAREN", "RPAREN", "DOT", "NEW", 
		"HELP", "TRUE", "FALSE", "NULL", "PLUS", "MINUS", "MULT", "DIV", "DOLLAR", 
		"INT", "LONG", "FLOAT", "DOUBLE", "ID", "WS", "STR", "CHAR", "ERROR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ConsoleParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ConsoleParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ConsoleParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ConsoleParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AssignmentContext : StatementContext {
		public IToken lhs;
		public ExprContext rhs;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(ConsoleParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ConsoleParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignmentContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExprStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ExprStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterExprStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitExprStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class HelpStatementContext : StatementContext {
		public IToken memberName;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HELP() { return GetToken(ConsoleParser.HELP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ConsoleParser.ID, 0); }
		public HelpStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterHelpStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitHelpStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHelpStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 0, RULE_statement);
		try {
			State = 14;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				_localctx = new AssignmentContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 8;
				((AssignmentContext)_localctx).lhs = Match(ID);
				State = 9;
				Match(EQ);
				State = 10;
				((AssignmentContext)_localctx).rhs = expr(0);
				}
				break;
			case 2:
				_localctx = new ExprStatementContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 11;
				expr(0);
				}
				break;
			case 3:
				_localctx = new HelpStatementContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 12;
				Match(HELP);
				State = 13;
				((HelpStatementContext)_localctx).memberName = Match(ID);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(ConsoleParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMI() { return GetTokens(ConsoleParser.SEMI); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI(int i) {
			return GetToken(ConsoleParser.SEMI, i);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 2, RULE_command);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 16;
			statement();
			State = 23;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SEMI) {
				{
				{
				State = 17;
				Match(SEMI);
				State = 19;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 58596898L) != 0)) {
					{
					State = 18;
					statement();
					}
				}

				}
				}
				State = 25;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 26;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CallContext : ExprContext {
		public IToken methodName;
		public ArgListContext args;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ConsoleParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		public CallContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NullExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(ConsoleParser.NULL, 0); }
		public NullExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterNullExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitNullExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNullExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumLiteralContext : ExprContext {
		public IToken literal;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(ConsoleParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(ConsoleParser.FLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(ConsoleParser.DOUBLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LONG() { return GetToken(ConsoleParser.LONG, 0); }
		public NumLiteralContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterNumLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitNumLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryOpContext : ExprContext {
		public IToken @operator;
		public ExprContext value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXCLAIM() { return GetToken(ConsoleParser.EXCLAIM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UnaryOpContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterUnaryOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitUnaryOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryOp(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NestedStatementExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOLLAR() { return GetToken(ConsoleParser.DOLLAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(ConsoleParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(ConsoleParser.RPAREN, 0); }
		public NestedStatementExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterNestedStatementExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitNestedStatementExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNestedStatementExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DotCallContext : ExprContext {
		public ExprContext dotExpr;
		public IToken methodName;
		public ArgListContext args;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(ConsoleParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ConsoleParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		public DotCallContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterDotCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitDotCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDotCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TextLiteralContext : ExprContext {
		public IToken literal;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STR() { return GetToken(ConsoleParser.STR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR() { return GetToken(ConsoleParser.CHAR, 0); }
		public TextLiteralContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterTextLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitTextLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolLiteralContext : ExprContext {
		public IToken literal;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(ConsoleParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(ConsoleParser.FALSE, 0); }
		public BoolLiteralContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterBoolLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitBoolLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LoneIdContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ConsoleParser.ID, 0); }
		public LoneIdContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterLoneId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitLoneId(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLoneId(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(ConsoleParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(ConsoleParser.RPAREN, 0); }
		public ParenExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterParenExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitParenExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 4;
		EnterRecursionRule(_localctx, 4, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				{
				_localctx = new LoneIdContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 29;
				Match(ID);
				}
				break;
			case 2:
				{
				_localctx = new NullExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 30;
				Match(NULL);
				}
				break;
			case 3:
				{
				_localctx = new ParenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 31;
				Match(LPAREN);
				State = 32;
				expr(0);
				State = 33;
				Match(RPAREN);
				}
				break;
			case 4:
				{
				_localctx = new NumLiteralContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 35;
				((NumLiteralContext)_localctx).literal = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 3932160L) != 0)) ) {
					((NumLiteralContext)_localctx).literal = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 5:
				{
				_localctx = new TextLiteralContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 36;
				((TextLiteralContext)_localctx).literal = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==STR || _la==CHAR) ) {
					((TextLiteralContext)_localctx).literal = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 6:
				{
				_localctx = new BoolLiteralContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 37;
				((BoolLiteralContext)_localctx).literal = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==TRUE || _la==FALSE) ) {
					((BoolLiteralContext)_localctx).literal = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 7:
				{
				_localctx = new NestedStatementExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 38;
				Match(DOLLAR);
				State = 39;
				Match(LPAREN);
				State = 40;
				statement();
				State = 41;
				Match(RPAREN);
				}
				break;
			case 8:
				{
				_localctx = new CallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 43;
				((CallContext)_localctx).methodName = Match(ID);
				State = 44;
				((CallContext)_localctx).args = argList();
				}
				break;
			case 9:
				{
				_localctx = new UnaryOpContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 45;
				((UnaryOpContext)_localctx).@operator = Match(EXCLAIM);
				State = 46;
				((UnaryOpContext)_localctx).value = expr(1);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 57;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new DotCallContext(new ExprContext(_parentctx, _parentState));
					((DotCallContext)_localctx).dotExpr = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 49;
					if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
					State = 50;
					Match(DOT);
					State = 51;
					((DotCallContext)_localctx).methodName = Match(ID);
					State = 53;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
					case 1:
						{
						State = 52;
						((DotCallContext)_localctx).args = argList();
						}
						break;
					}
					}
					} 
				}
				State = 59;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArgListContext : ParserRuleContext {
		public ExprContext _expr;
		public IList<ExprContext> _args = new List<ExprContext>();
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(ConsoleParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(ConsoleParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(ConsoleParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(ConsoleParser.COMMA, i);
		}
		public ArgListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.EnterArgList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConsoleParserListener typedListener = listener as IConsoleParserListener;
			if (typedListener != null) typedListener.ExitArgList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IConsoleParserVisitor<TResult> typedVisitor = visitor as IConsoleParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgListContext argList() {
		ArgListContext _localctx = new ArgListContext(Context, State);
		EnterRule(_localctx, 6, RULE_argList);
		int _la;
		try {
			State = 73;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 60;
				Match(LPAREN);
				State = 69;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 58596386L) != 0)) {
					{
					State = 61;
					_localctx._expr = expr(0);
					_localctx._args.Add(_localctx._expr);
					State = 66;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==COMMA) {
						{
						{
						State = 62;
						Match(COMMA);
						State = 63;
						_localctx._expr = expr(0);
						_localctx._args.Add(_localctx._expr);
						}
						}
						State = 68;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 71;
				Match(RPAREN);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 72;
				_localctx._expr = expr(0);
				_localctx._args.Add(_localctx._expr);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 2: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 7);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,26,76,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,1,0,1,0,1,0,1,0,1,0,3,0,
		15,8,0,1,1,1,1,1,1,3,1,20,8,1,5,1,22,8,1,10,1,12,1,25,9,1,1,1,1,1,1,2,
		1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
		2,3,2,48,8,2,1,2,1,2,1,2,1,2,3,2,54,8,2,5,2,56,8,2,10,2,12,2,59,9,2,1,
		3,1,3,1,3,1,3,5,3,65,8,3,10,3,12,3,68,9,3,3,3,70,8,3,1,3,1,3,3,3,74,8,
		3,1,3,0,1,4,4,0,2,4,6,0,3,1,0,18,21,1,0,24,25,1,0,10,11,88,0,14,1,0,0,
		0,2,16,1,0,0,0,4,47,1,0,0,0,6,73,1,0,0,0,8,9,5,22,0,0,9,10,5,2,0,0,10,
		15,3,4,2,0,11,15,3,4,2,0,12,13,5,9,0,0,13,15,5,22,0,0,14,8,1,0,0,0,14,
		11,1,0,0,0,14,12,1,0,0,0,15,1,1,0,0,0,16,23,3,0,0,0,17,19,5,4,0,0,18,20,
		3,0,0,0,19,18,1,0,0,0,19,20,1,0,0,0,20,22,1,0,0,0,21,17,1,0,0,0,22,25,
		1,0,0,0,23,21,1,0,0,0,23,24,1,0,0,0,24,26,1,0,0,0,25,23,1,0,0,0,26,27,
		5,0,0,1,27,3,1,0,0,0,28,29,6,2,-1,0,29,48,5,22,0,0,30,48,5,12,0,0,31,32,
		5,5,0,0,32,33,3,4,2,0,33,34,5,6,0,0,34,48,1,0,0,0,35,48,7,0,0,0,36,48,
		7,1,0,0,37,48,7,2,0,0,38,39,5,17,0,0,39,40,5,5,0,0,40,41,3,0,0,0,41,42,
		5,6,0,0,42,48,1,0,0,0,43,44,5,22,0,0,44,48,3,6,3,0,45,46,5,1,0,0,46,48,
		3,4,2,1,47,28,1,0,0,0,47,30,1,0,0,0,47,31,1,0,0,0,47,35,1,0,0,0,47,36,
		1,0,0,0,47,37,1,0,0,0,47,38,1,0,0,0,47,43,1,0,0,0,47,45,1,0,0,0,48,57,
		1,0,0,0,49,50,10,7,0,0,50,51,5,7,0,0,51,53,5,22,0,0,52,54,3,6,3,0,53,52,
		1,0,0,0,53,54,1,0,0,0,54,56,1,0,0,0,55,49,1,0,0,0,56,59,1,0,0,0,57,55,
		1,0,0,0,57,58,1,0,0,0,58,5,1,0,0,0,59,57,1,0,0,0,60,69,5,5,0,0,61,66,3,
		4,2,0,62,63,5,3,0,0,63,65,3,4,2,0,64,62,1,0,0,0,65,68,1,0,0,0,66,64,1,
		0,0,0,66,67,1,0,0,0,67,70,1,0,0,0,68,66,1,0,0,0,69,61,1,0,0,0,69,70,1,
		0,0,0,70,71,1,0,0,0,71,74,5,6,0,0,72,74,3,4,2,0,73,60,1,0,0,0,73,72,1,
		0,0,0,74,7,1,0,0,0,9,14,19,23,47,53,57,66,69,73
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Terasievert.AbonConsole.AntlrGenerated
