//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConsoleParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Terasievert.AbonConsole.AntlrGenerated {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IConsoleParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ConsoleParserBaseListener : IConsoleParserListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] ConsoleParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] ConsoleParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStatement([NotNull] ConsoleParser.ExprStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStatement([NotNull] ConsoleParser.ExprStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>helpStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHelpStatement([NotNull] ConsoleParser.HelpStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>helpStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHelpStatement([NotNull] ConsoleParser.HelpStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ConsoleParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] ConsoleParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ConsoleParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] ConsoleParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] ConsoleParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] ConsoleParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>nullExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullExpr([NotNull] ConsoleParser.NullExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nullExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullExpr([NotNull] ConsoleParser.NullExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>numLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumLiteral([NotNull] ConsoleParser.NumLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>numLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumLiteral([NotNull] ConsoleParser.NumLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOp([NotNull] ConsoleParser.UnaryOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOp([NotNull] ConsoleParser.UnaryOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>nestedStatementExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedStatementExpr([NotNull] ConsoleParser.NestedStatementExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nestedStatementExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedStatementExpr([NotNull] ConsoleParser.NestedStatementExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>dotCall</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotCall([NotNull] ConsoleParser.DotCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>dotCall</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotCall([NotNull] ConsoleParser.DotCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>textLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLiteral([NotNull] ConsoleParser.TextLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>textLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLiteral([NotNull] ConsoleParser.TextLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boolLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolLiteral([NotNull] ConsoleParser.BoolLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolLiteral([NotNull] ConsoleParser.BoolLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loneId</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoneId([NotNull] ConsoleParser.LoneIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loneId</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoneId([NotNull] ConsoleParser.LoneIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] ConsoleParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] ConsoleParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ConsoleParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] ConsoleParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ConsoleParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] ConsoleParser.ArgListContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Terasievert.AbonConsole.AntlrGenerated
