//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConsoleParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Terasievert.AbonConsole.AntlrGenerated {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ConsoleParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IConsoleParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] ConsoleParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStatement([NotNull] ConsoleParser.ExprStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>helpStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHelpStatement([NotNull] ConsoleParser.HelpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] ConsoleParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] ConsoleParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nullExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullExpr([NotNull] ConsoleParser.NullExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumLiteral([NotNull] ConsoleParser.NumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOp([NotNull] ConsoleParser.UnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nestedStatementExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedStatementExpr([NotNull] ConsoleParser.NestedStatementExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dotCall</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotCall([NotNull] ConsoleParser.DotCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>textLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextLiteral([NotNull] ConsoleParser.TextLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boolLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLiteral([NotNull] ConsoleParser.BoolLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>loneId</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoneId([NotNull] ConsoleParser.LoneIdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] ConsoleParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ConsoleParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] ConsoleParser.ArgListContext context);
}
} // namespace Terasievert.AbonConsole.AntlrGenerated
