//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConsoleParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Terasievert.AbonConsole.AntlrGenerated {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ConsoleParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IConsoleParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] ConsoleParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] ConsoleParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStatement([NotNull] ConsoleParser.ExprStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStatement([NotNull] ConsoleParser.ExprStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>helpStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHelpStatement([NotNull] ConsoleParser.HelpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>helpStatement</c>
	/// labeled alternative in <see cref="ConsoleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHelpStatement([NotNull] ConsoleParser.HelpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ConsoleParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] ConsoleParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ConsoleParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] ConsoleParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] ConsoleParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] ConsoleParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>nullExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullExpr([NotNull] ConsoleParser.NullExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nullExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullExpr([NotNull] ConsoleParser.NullExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumLiteral([NotNull] ConsoleParser.NumLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumLiteral([NotNull] ConsoleParser.NumLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOp([NotNull] ConsoleParser.UnaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOp([NotNull] ConsoleParser.UnaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>nestedStatementExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedStatementExpr([NotNull] ConsoleParser.NestedStatementExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nestedStatementExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedStatementExpr([NotNull] ConsoleParser.NestedStatementExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>dotCall</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotCall([NotNull] ConsoleParser.DotCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>dotCall</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotCall([NotNull] ConsoleParser.DotCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>textLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextLiteral([NotNull] ConsoleParser.TextLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>textLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextLiteral([NotNull] ConsoleParser.TextLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolLiteral([NotNull] ConsoleParser.BoolLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolLiteral</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolLiteral([NotNull] ConsoleParser.BoolLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>loneId</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoneId([NotNull] ConsoleParser.LoneIdContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>loneId</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoneId([NotNull] ConsoleParser.LoneIdContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] ConsoleParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="ConsoleParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] ConsoleParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ConsoleParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] ConsoleParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ConsoleParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] ConsoleParser.ArgListContext context);
}
} // namespace Terasievert.AbonConsole.AntlrGenerated
